export const CHANGE_STATE = "CHANGE_STATE";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
export const GET_SLIDER_SUCCESS = "GET_SLIDER_SUCCESS";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
